version: '3'

services:
  # if using database, set the service-name and image to be used from docker hub
  # [service-name]:
  #   image: [database-image-name]
  #
  # example:
  # postgres_db:
  #   image: postgres
  #   container_name: postgres_container_id
  # set the service name for django
  # In this document, the project_name maches with the service name
  # for Django framework
  # [project_name]:
  # example:
  website_name:
    container_name: django_web_id
    # for envirment variables
    env_file:
      - .env
    build: .
    # The commands include the bare minimun for a Django project, such as migrations and static collection
    #
    # NOTE: you have to setup the STATIC_ROOT in the project settings, otherwise the service won't run
    command: bash -c 
      "
      python3 manage.py makemigrations &&
      python3 manage.py migrate && 
      yes yes | python3 manage.py collectstatic &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    # Change project_name for the actual name of the project
    volumes:
      - .:/www/project_name
    ports:
      - "8000:8000"
    # If a database is being used, set the service name here
    # depends_on:
    #   - [service-name]
    #
    # example:
    # depends_on:
    #   - postgres_db